apiVersion: v1
kind: Service
metadata:
  name: keda-add-ons-http-interceptor-proxy
  namespace: keda
spec:
  type: ClusterIP
  ports:
    - name: proxy-tls
      protocol: TCP
      port: 8443
      targetPort: proxy-tls
