apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- metrics.service.yaml
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/instance: operator
