apiVersion: v1
kind: Service
metadata:
  name: operator-metrics
spec:
  type: ClusterIP
  # TODO: selector must match pod template labels, fix together with
  # deployment selector.matchLabels when breaking change is acceptable.
  selector:
    app.kubernetes.io/component: add-on
    app.kubernetes.io/instance: operator
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: keda
  ports:
    - name: metrics-http
      protocol: TCP
      port: 8080
      targetPort: metrics-http
    - name: metrics-https
      protocol: TCP
      port: 8443
      targetPort: metrics-https
