apiVersion: v1
kind: Service
metadata:
  name: operator-metrics
spec:
  type: ClusterIP
  ports:
  - name: metrics-http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics-https
    protocol: TCP
    port: 8443
    targetPort: 8443
