apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
patches:
  - path: otel/interceptor-deployment.yaml
  - path: otel/interceptor-scaledobject.yaml
  - path: otel/scaler-deployment.yaml
  - path: tls/interceptor-deployment.yaml
  - path: tls/proxy-service.yaml
