apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- role.yaml
- role_binding.yaml
- service.yaml
- service_account.yaml
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/instance: external-scaler
images:
- name: ghcr.io/kedacore/http-add-on-scaler
  newName: ghcr.io/kedacore/http-add-on-scaler
  newTag: e27715294f290393467504e5329bcb1bc42116fe
patches:
- path: e2e-test/otel/deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: scaler
    version: v1
