blank_issues_enabled: true
contact_links:
  - name: Ask a question about KEDA HTTP Add-on or get support
    url: https://github.com/kedacore/http-add-on/discussions/new
    about: Ask a question or request support for using KEDA HTTP Add-on
