apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- role.yaml
- role_binding.yaml
- admin.service.yaml
- proxy.service.yaml
- service_account.yaml
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/instance: interceptor
images:
- name: ghcr.io/kedacore/http-add-on-interceptor
  newName: ghcr.io/kedacore/http-add-on-interceptor
  newTag: main
