apiVersion: v1
kind: Service
metadata:
  name: interceptor-proxy
spec:
  type: ClusterIP
  # TODO: selector must match pod template labels, fix together with
  # deployment selector.matchLabels when breaking change is acceptable.
  selector:
    app.kubernetes.io/component: add-on
    app.kubernetes.io/instance: interceptor
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: keda
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: proxy
