---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: interceptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: interceptor
subjects:
  - kind: ServiceAccount
    name: interceptor
