apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: interceptor-proxy
    app.kubernetes.io/name: keda-http-add-on
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-http-add-on
  name: keda-http-add-on-interceptor-proxy
  namespace: keda
spec:
  ports:
  - name: https
    port: 8080
    targetPort: inter-proxy
  selector:
    control-plane: interceptor
