apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: interceptor-admin
    app.kubernetes.io/name: keda-http-add-on
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-http-add-on
  name: keda-http-add-on-interceptor-admin
  namespace: keda
spec:
  ports:
  - name: https
    port: 9090
    targetPort: inter-admin
  selector:
    control-plane: interceptor