name: Publish official image to GitHub Container Registry

on:
  push:
    tags: [ "v[0-9].[0-9].[0-9]" ]

env:
  IMAGE_OPERATOR_NAME: ghcr.io/${{ github.repository_owner }}/http-add-on-operator
  IMAGE_INTERCEPTOR_NAME: ghcr.io/${{ github.repository_owner }}/http-add-on-interceptor
  IMAGE_SCALER_NAME: ghcr.io/${{ github.repository_owner }}/http-add-on-scaler

jobs:
  build_operator:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up tags and refs
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ github.repository_owner }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.GITHUB_TOKEN }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io

      - name: Build and push operator image
        uses: docker/build-push-action@v2
        with:
          # Docker repository to tag the image with
          tags: ${{ env.IMAGE_OPERATOR_NAME }}:latest,${{ env.IMAGE_OPERATOR_NAME }}:${{ steps.get_version.outputs.VERSION }}
          labels: |
            sh.keda.http.image.source=${{github.event.repository.html_url}}
            sh.keda.http.image.created=${{steps.prep.outputs.created}}
            sh.keda.http.image.revision=${{github.sha}}
            sh.keda.http.image.release=${{github.ref}}
          build-args: "VERSION=${{ steps.prep.outputs.VERSION }}"
          file: operator/Dockerfile
          context: .
          push: true

  build_interceptor:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up tags and refs
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ github.repository_owner }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.GITHUB_TOKEN }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io

      - name: Build and push interceptor image
        uses: docker/build-push-action@v2
        with:
          # Docker repository to tag the image with
          tags: ${{ env.IMAGE_INTERCEPTOR_NAME }}:latest,${{ env.IMAGE_INTERCEPTOR_NAME }}:${{ steps.get_version.outputs.VERSION }}
          labels: |
            sh.keda.http.image.source=${{github.event.repository.html_url}}
            sh.keda.http.image.created=${{steps.prep.outputs.created}}
            sh.keda.http.image.revision=${{github.sha}}
            sh.keda.http.image.release=${{github.ref}}
          file: interceptor/Dockerfile
          context: .
          push: true

  build_scaler:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up tags and refs
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ github.repository_owner }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.GITHUB_TOKEN }}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io

      - name: Build and push scaler image
        uses: docker/build-push-action@v2
        with:
          # Docker repository to tag the image with
          tags: ${{ env.IMAGE_SCALER_NAME }}:latest,${{ env.IMAGE_SCALER_NAME }}:${{ steps.get_version.outputs.VERSION }}
          labels: |
            sh.keda.http.image.source=${{github.event.repository.html_url}}
            sh.keda.http.image.created=${{steps.prep.outputs.created}}
            sh.keda.http.image.revision=${{github.sha}}
            sh.keda.http.image.release=${{github.ref}}
          file: scaler/Dockerfile
          context: .
          push: true

  e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Helm install
        uses: Azure/setup-helm@v1

      - name: Create k8s v1.23 Kind Cluster
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
          cluster_name: http-add-on-smoke-tests-cluster

      - name: Run e2e test
        run: |
          ./tests/e2e-test.sh
        env:
          TAG: ${{ steps.get_version.outputs.VERSION }}
